name: Usage with npm

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install client publish with npm
        run: npm install @emartech/client-publish
      - name: Run client publish
        run: node node_modules/.bin/client-publish
